version: "3"

services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGOURI=mongodb+srv://brandDiscountsUser:brandDiscountsPassword@cluster0.jnnrd.mongodb.net/desafio_walmart?authSource=admin&replicaSet=atlas-10hsq0-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true
    ports:
      - 5000:5000
    network_mode: "host"

  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend
    ports:
      - 3000:3000
    network_mode: "host"
